package com.myla.common.api.event;

public enum LabEvent {
    SAMPLE_REGISTERED,
    SAMPLE_RECEIVED,
    CULTURE_POSITIVE,
    CULTURE_NEGATIVE,
    ORGANISM_IDENTIFIED,
    AST_RESULT_RECEIVED,
    RESULT_APPROVED,
    RESULT_RELEASED_TO_LIS,
    CRITICAL_VALUE_DETECTED,
    TAT_THRESHOLD_EXCEEDED,
    SAMPLE_MISMATCH,
    QC_OUT_OF_RANGE
}
