server:
  port: 8081

spring:
  application:
    name: capl
  config:
    import:
      - optional:nacos:capl.yml
      - optional:nacos:capl-${spring.profiles.active}.yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PASS:root}
    publisher-confirm-type: correlated
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:}

# 通讯层配置（以下为本地默认值，Nacos 中同名配置会覆盖此处）
lis-comm:
  driver-dir: ./drivers       # 驱动插件 JAR 目录
  instruments: []             # 仪器列表 → 生产环境建议在 Nacos 中管理

  lis-inbound:
    - hospitalCode: DEMO_HOSPITAL
      port: 2575

  lis-outbound: []
