server:
  port: 8081

spring:
  application:
    name: capl
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PASS:root}

# 通讯层配置
lis-comm:
  instruments: []

  lis-inbound:
    - hospitalCode: DEMO_HOSPITAL
      port: 2575

  lis-outbound: []
