<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.myla</groupId>
        <artifactId>myla-platform</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>myla-platform-gateway</artifactId>
    <packaging>pom</packaging>
    <name>MYLA Platform Gateway</name>
    <modules>
        <module>gateway-core</module>
        <module>gateway-channel</module>
        <module>gateway-splitter</module>
        <module>gateway-protocol</module>
        <module>gateway-device-mgmt</module>
        <module>gateway-drivers</module>
    </modules>
</project>
